version: 2

sources:
  - name: raw  
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales

        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
    
        tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"

        columns:
          - name: orders_id
            tests:
              - not_null
        
          - name: pdt_id
            tests:
              - not_null

      - name: product
        identifier: raw_gz_product

        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      
      - name: ship
        identifier: raw_gz_ship

        columns:
          - name: orders_id
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
      
      - name: bing
        identifier: raw_gz_bing

      - name: criteo
        identifier: raw_gz_criteo

      - name: facebook
        identifier: raw_gz_facebook